eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true   #打开Feign自带的断路器
  #feign的配置，连接超时及读取超时配置
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic